apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: postmortem
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers: 
      - name: db-container
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD 
          value: example
        ports:
          - name: mongodb-port
            containerPort: 27017
            protocol: TCP
